version = 1.6

clean:
	del donuts\*.class
donut:
	javac -source $(version) -target $(version) -Xlint:options donuts\Donut.java
cupcake:
	javac -source $(version) -target $(version) Xlint:options cupcake\Cupcake.java

do: donut cupcake
all: clean do
