/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Summer */

#ifndef _Included_Summer
#define _Included_Summer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Summer
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Summer_sum
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
