oapath = -I"C:\Documents and Settings\Laboratorio.LABORATO-6A7377\Meus documentos\software\EEG\src"
options = -lm -O2 -ansi -pipe -Wall

edf2ascii.exe: edf2ascii.c
	gcc edf2ascii.c -o edf2ascii.exe $(options) $(oapath)