do: ascii

hct:
	python main.csv.py < HCT-4-23.csv

camila:
	python main.csv.py < camila.csv

sine:
	python sinewave.py

ascii:
	python main.ascii.py < HCT-4-23.ascii

clean:
	rm *.png
	rm camila.csv
