oapath = -I".."
options = -lm -O2 -ansi -pipe -Wall

some2ascii.exe: some2ascii.c some2ascii.h
	gcc some2ascii.c -o some2ascii.exe $(options) $(oapath)
csv2ascii.exe: csv2ascii.c csv2ascii.h
	gcc csv2ascii.c -o csv2ascii.exe $(options) $(oapath)
csv2fullascii.exe: csv2fullascii.c csv2fullascii.h
	gcc csv2fullascii.c -o csv2fullascii.exe $(options) $(oapath)