oapath = -I"C:\Documents and Settings\Laboratorio.LABORATO-6A7377\Meus documentos\software\EEG\src"
options = -lm -O2 -ansi -pipe -Wall

some2ascii.exe: some2ascii.c some2ascii.h
	gcc some2ascuu.c -o some2ascii.exe $(options) $(oapath)
csv2ascii.exe: csv2ascii.c csv2ascii.h
	gcc csv2ascii.c -o csv2ascii.exe $(options) $(oapath)
