
dwt_enable=1;
v7errorfile=0;
v7numsig=1;
v7wname='haar';
h7axapdet=[];
v7nedit=1;
v7editmx=[];
v7plotrec=[];
v7letra=9;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%PAINEL FRONTAL%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7dwt=figure('units','normalized',...
    'position',[0.0038,0.0495,0.993,0.89],...
    'menubar','none',...
    'numbertitle','off',...
    'name','Módulo DWT',...
    'color','white',...
    'deletefcn','clear h7* f7* v7*;dwt_enable=0;');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%MENU%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7menuarquivo=uimenu('label','Arquivo');

f7errorsignal_fcn=['beep;'...
        'msgbox(''O arquivo nao tem formato compativel'',''Arquivo invalido'',''warn'');'...
        'v7errorfile=1;'];

f7adicionar_fcn=['[v7signalext,v7filepath]=uigetfile(''*.ascii'',''Escolha o arquivo do registro'');'...
        'switch ischar(v7signalext);'...
            'case 0;'...
                'return;'...
        'end;'...
        'v7file=strcat(v7filepath,v7signalext);'...
        'eval(''load(v7file)'',f7errorsignal_fcn);'...
        'if v7errorfile==1;'...
            'v7errorfile=0;'...
            'return;'...
        'end;'...
        'v7signalname=v7signalext(1:length(v7signalext)-6);'...
        'set(h7signaltxt,''string'',strcat(''Sinal:'',v7signalname));'...
        'set(h7fstxt,''string'',strcat(''Fs [Hz]:'',num2str(fs)));'...
        'v7presignal=eval(v7signalname);'...
        'v7signal=((v7presignal+fa)*fb)-fc;'...
        'v7lensig=length(v7signal);'...
        'v7t=0:1/fs:(v7lensig-1)/fs;'...
        'v7treg=str2num(sprintf(''%4.2f'',max(v7t)));'...
        'set(h7tregtxt,''string'',strcat(''Tempo de registro:'',num2str(v7treg),'' [s]''));'...
        'v7plotsig=plot(v7t,v7signal,''k'');'...
        'axis tight;'...
        'grid on;'...
        'set([h7tipowavetxt h7reset h7tipowave h7laveltxt h7level h7calcular],''enable'',''on'');'];


h7adicionar=uimenu(h7menuarquivo,'label','Adicionar Sinal','callback',f7adicionar_fcn);
h7sair=uimenu(h7menuarquivo,'label','Sair','separator','on');

h7ver=uimenu('label','Ver','enable','off');

f7original_fcn=['switch strcmp(''on'',get(h7original,''checked''));'...
        'case 1;'...
            'set(v7plotsig,''visible'',''off'');'...
            'set(h7original,''checked'',''off'');'...
        'case 0;'...
            'set(v7plotsig,''visible'',''on'');'...
            'set(h7original,''checked'',''on'');'...
     'end;'];
h7original=uimenu(h7ver,'label','Sinal original','checked','on','callback',f7original_fcn);

f7recon_fcn=['switch strcmp(''on'',get(h7recon,''checked''));'...
        'case 1;'...
            'set(v7plotrec,''visible'',''off'');'...
            'set(h7recon,''checked'',''off'');'...
            'set([h7saverecfig h7saverec],''enable'',''off'');'...
        'case 0;'...
            'set(v7plotrec,''visible'',''on'');'...
            'set(h7recon,''checked'',''on'');'...
            'set([h7saverecfig h7saverec],''enable'',''on'');'...
     'end;'];
h7recon=uimenu(h7ver,'label','Reconstrucao','checked','on','callback',f7recon_fcn);

f7decom_fcn=['switch strcmp(''on'',get(h7decom,''checked''));'...
        'case 1;'...
            'set([h7axapdet v7plotapdet],''visible'',''off'');'...
            'set(h7axesini,''position'',[0.056,0.165,0.755,0.76]);'...
            'set(h7decom,''checked'',''off'');'...
            'set([h7desfazer h7editar h7salvarfig h7salvar],''enable'',''off'');'...
        'case 0;'...
            'set([h7axapdet v7plotapdet],''visible'',''on'');'...
            'set(h7axesini,''position'',v7originpos);'...
            'set(h7decom,''checked'',''on'');'...
            'set([h7desfazer h7editar h7salvarfig h7salvar],''enable'',''on'');'...
     'end;'];
 h7decom=uimenu(h7ver,'label','Decomposicao','callback',f7decom_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%AXESINI%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

v7hini=0.76;
h7axesini=axes('units','normalized',...
    'position',[0.056,0.165,0.755,0.76],...
    'box','on');
grid on;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SIGNALINFO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7frame1=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.056,0.95,0.755,0.04]);

h7signaltxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.06,0.96,0.16,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'HorizontalAlignment','left',...
    'string','Sinal:');

h7fstxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.25,0.96,0.1,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'HorizontalAlignment','left',...
    'string','Fs [Hz]:');

h7tregtxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.38,0.96,0.16,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'HorizontalAlignment','left',...
    'string','Tempo de registro [s]:');

h7wavetxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.57,0.96,0.16,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'HorizontalAlignment','left',...
    'string','Wavelet:Haar');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%WAVECONFIG%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7frame2=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.822,0.78,0.17,0.21]);

h7waveletlabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.827,0.96,0.15,0.023],...
    'fontname','arial',...
    'fontsize',v7letra+1,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','CONFIGURACAO WAVELET');

v7waveoptions={'Haar','Daubechies','Symlets','Coiflets','Biorthogonal','R_Biorthogonal'};
v7dboptions={'db1','db2','db3','db4','db5','db6','db7','db8','db9','db10'};
v7bioroptions={'1.1','1.3','1.5','2.2','2.4','2.6','2.8','3.1','3.3','3.5','3.7','3.9','4.4','5.5','6.8'};
v7rbiooptions=v7bioroptions;
v7symoptions={'2','3','4','5','6','7','8'};
v7coifoptions={'1','2','3','4','5'};

f7tipowave_fcn=['switch get(h7tipowave,''value'');'...
        'case 1;'...
            'set(h7paramwave,''visible'',''off'',''value'',1);'...
            'v7wname=''haar'';'...
        'case 2;'...
            'set(h7paramwave,''visible'',''on'',''value'',1,''string'',v7dboptions);'...
            'v7wname=''db1'';'...
        'case 3;'...
            'set(h7paramwave,''visible'',''on'',''value'',1,''string'',v7symoptions);'...
            'v7wname=''sym2'';'...
        'case 4;'...
            'set(h7paramwave,''visible'',''on'',''value'',1,''string'',v7coifoptions);'...
            'v7wname=''coif1'';'...
        'case 5;'...
            'set(h7paramwave,''visible'',''on'',''value'',1,''string'',v7bioroptions);'...
            'v7wname=''bior1.1'';'...
        'case 6;'...
            'set(h7paramwave,''visible'',''on'',''value'',1,''string'',v7rbiooptions);'...
            'v7wname=''rbio1.1'';'...
    'end;'...
    'set(h7wavetxt,''string'',strcat(''Wavelet:'',v7wname));'];

h7tipowavetxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.832,0.935,0.13,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','Tipo de Wavelet');

h7tipowave=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'units','normalized',...
    'position',[0.832,0.86,0.105,0.07],...
    'string',v7waveoptions,...
    'callback',f7tipowave_fcn);

f7param_fcn=['v7param=get(h7paramwave,''value'');'...
    'switch get(h7tipowave,''value'');'...
        'case 2;'...
            'v7wname=strcat(''db'',num2str(v7param));'...
        'case 3;'...
            'v7wname=strcat(''sym'',num2str(v7param+1));'...
        'case 4;'...
            'v7wname=strcat(''coif'',num2str(v7param));'...
        'case 5;'...
            'v7wname=strcat(''bior'',v7bioroptions{v7param});'...
        'case 6;'...
            'v7wname=strcat(''rbio'',v7bioroptions{v7param});'...
    'end;'...
    'set(h7wavetxt,''string'',strcat(''Wavelet:'',v7wname));'];

h7paramwave=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'visible','off',...
    'units','normalized',...
    'position',[0.94,0.86,0.038,0.07],...
    'string',v7dboptions,...
    'callback',f7param_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%CALCULAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7laveltxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.872,0.86,0.05,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','Nivel');

h7level=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'units','normalized',...
    'enable','off',...
    'position',[0.9,0.82,0.038,0.07],...
    'string','1|2|3|4|5|6|7|8|9|10');

f7calcular_fcn=['switch isempty(h7axapdet);'...
        'case 0;'...
            'delete(h7axapdet);'...
            'clear v7plotapdet;'...
            'h7axapdet=[];'...
            'set(h7axesini,''position'',[0.056,0.165,0.755,0.76]);'...
            'set(h7selsignal,''value'',1,''string'',''Nenhum'');'...
            'set([h7pfinalvalue h7pinicialvalue],''string'',''1'');'...
            'v7editmx=[];'...
            'h7cdataedit=[];'...
            'set([h7editsignaltxt h7selsignal h7edittodo h7editintervalo h7pinicialtxt h7pinicialvalue h7pfinaltxt],''enable'',''off'');'...
            'set([h7pfinalvalue h7v1txt h7v1value h7editar h7desfazer h7limitar h7limitarhist h7substituir],''enable'',''off'');'...
            'set(h7salvarsignal,''value'',1,''string'',''N/A'');'...
            'set([h7salvar h7salvarfig h7salvartxt h7salvarsignal],''enable'',''off'');'...
    'end;'...
    'switch isempty(v7plotrec);'...
        'case 0;'...
            'delete(v7plotrec);'...
            'v7plotrec=[];'...
            'set([h7saverecfig h7saverec],''enable'',''off'');'...
    'end;'...
    'v7sigselect=[];'...
    'v7level=get(h7level,''value'');'...
    'v7apxname={};'...
    'v7detname={};'...
    'for i=1:v7level;'...
        'v7apxname{i,1}=strcat(''cA'',num2str(i));'...
        'v7apxname{i,2}=strcat(''A'',num2str(i));'...
        'v7apxname{i,3}=1;'...
        'v7apxname{i,4}=i;'...
        'v7detname{i,1}=strcat(''cD'',num2str(i));'...
        'v7detname{i,2}=strcat(''D'',num2str(i));'...
        'v7detname{i,3}=0;'...
        'v7detname{i,4}=i;'...
    'end;'...
    'set(h7veropt,''value'',1);'...
    'set(h7listaprox,''string'',v7apxname(:,1));'...
    'set(h7listdetalhes,''string'',v7detname(:,1));'...
    'set(h7listatotal,''value'',1,''string'',''Nenhum'');'...
    '[v7c v7l]=wavedec(v7signal,v7level,v7wname);'...
    'set(h7zoombutton,''enable'',''off'',''value'',0);'...
    'set(h7zoom,''enable'',''off'');'...
    'set([h7addaprox h7listatotaltxt h7listdetalhes h7addetalhe h7listatotal h7remover h7visualizar],''enable'',''on'');'...
    'set([h7veropt h7veraproxradio h7verdetalradio h7verdefradio h7aproxtxt h7listaprox h7detatxt],''enable'',''on'');'...
    'eval(f7radioverdef_fcn);'];

h7calcular=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'string','Calcular',...
    'position',[0.872,0.795,0.08,0.05],...
    'callback',f7calcular_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%VISUALIZAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


h7frame3=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.822,0.13,0.17,0.635]);

h7visuallabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.827,0.73,0.15,0.023],...
    'fontname','arial',...
    'fontsize',v7letra+1,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','VISUALIZAR');

f7veropt_fcn=['switch get(h7veropt,''value'');'...
        'case 1;'...
            'set(h7listaprox,''string'',v7apxname(:,1));'...
            'set(h7listdetalhes,''string'',v7detname(:,1));'...
        'case 2;'...
            'set(h7zoomconj,''enable'',''off'',''value'',0);'...
            'set(h7zoomind,''value'',1);'...
            'set(h7listaprox,''string'',v7apxname(:,2));'...
            'set(h7listdetalhes,''string'',v7detname(:,2));'...
            'set([h7editsignaltxt h7selsignal h7edittodo h7editintervalo h7pinicialtxt h7pinicialvalue h7pfinaltxt],''enable'',''off'');'...
            'set([h7pfinalvalue h7v1txt h7v1value h7limitar h7limitarhist h7substituir h7editar],''enable'',''off'');'...
     'end;'...
     'set([h7verdetalradio h7veraproxradio],''value'',0);'...
     'set(h7verdefradio,''value'',1);'...
     'set(h7listatotal,''value'',1,''string'',''Nenhum'');'...
     'v7numsig=1;'...
     'set(h7zoombutton,''enable'',''off'',''value'',0);'...
     'set(h7zoom,''enable'',''off'');'...
     'v7sigselect={};'];

h7veropt=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'units','normalized',...
    'position',[0.84,0.65,0.13,0.07],...
    'string','Coeficientes|Reconstrucoes',...
    'callback',f7veropt_fcn);

f7radioveraprox_fcn=['switch get(h7veraproxradio,''value'');'...
        'case 1;'...
            'set([h7verdetalradio h7verdefradio],''value'',0);'...
            'set(h7zoombutton,''enable'',''off'',''value'',0);'...
            'set(h7zoom,''enable'',''off'');'...
            'v7sigselect={};'...
            'switch get(h7veropt,''value'');'...
                'case 1;'...
                    'v7sigselect=v7apxname(:,1);'...
                'case 2;'...
                    'v7sigselect=v7apxname(:,2);'...
            'end;'...
            'v7sigselect(:,2)=v7apxname(:,3);'...
            'v7sigselect(:,3)=v7apxname(:,4);'...
            'v7numsig=v7level+1;'...
            'set(h7listatotal,''value'',1,''string'',get(h7listaprox,''string''));'...
        'case 0;'...
            'set(h7veraproxradio,''value'',1);'...
    'end;'];

h7veraproxradio=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.827,0.66,0.09,0.02],...
    'string','Aproximacoes',...
    'callback',f7radioveraprox_fcn);

f7radioverdetal_fcn=['switch get(h7verdetalradio,''value'');'...
        'case 1;'...
            'set([h7veraproxradio h7verdefradio],''value'',0);'...
            'set(h7zoombutton,''enable'',''off'',''value'',0);'...
            'set(h7zoom,''enable'',''off'');'...
            'v7sigselect={};'...
            'switch get(h7veropt,''value'');'...
                'case 1;'...
                    'v7sigselect=v7detname(:,1);'...
                'case 2;'...
                    'v7sigselect=v7detname(:,2);'...
            'end;'...
            'v7sigselect(:,2)=v7detname(:,3);'...
            'v7sigselect(:,3)=v7detname(:,4);'...
            'set(h7listatotal,''value'',1,''string'',get(h7listdetalhes,''string''));'...
            'v7numsig=v7level+1;'...
        'case 0;'...
            'set(h7verdetalradio,''value'',1);'...
    'end;'];

h7verdetalradio=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.827,0.63,0.09,0.02],...
    'string','Detalhes',...
    'callback',f7radioverdetal_fcn);

f7radioverdef_fcn=['switch get(h7verdefradio,''value'');'...
        'case 1;'...
            'set(h7zoombutton,''enable'',''off'',''value'',0);'...
            'set(h7zoom,''enable'',''off'');'...
            'v7sigselect={};'...
            'v7numsig=1;'...
            'set(h7listatotal,''value'',1,''string'',''Nenhum'');'...
        'case 0;'...
            'set(h7verdefradio,''value'',1);'...
    'end;'...
    'set([h7verdetalradio h7veraproxradio],''value'',0);'];

h7verdefradio=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'value',1,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.827,0.6,0.09,0.02],...
    'string','Definir',...
    'callback',f7radioverdef_fcn);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%VISUALIZAR Definir%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7aproxtxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.827,0.563,0.065,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','Aproximacoes');

h7listaprox=uicontrol('style','listbox',...
    'units','normalized',...
    'position',[0.827,0.46,0.077,0.1],...
    'backgroundcolor','white',...
    'enable','off',...
    'string','Nenhum');

f7addapx_fcn=['v7apxselect=get(h7listaprox,''value'');'...
    'switch get(h7veropt,''value'');'...
        'case 1;'...
            'v7sigselect{v7numsig,1}=v7apxname{v7apxselect,1};'...
        'case 2;'...
            'v7sigselect{v7numsig,1}=v7apxname{v7apxselect,2};'...
    'end;'...
    'v7sigselect{v7numsig,2}=1;'...
    'v7sigselect{v7numsig,3}=v7apxname{v7apxselect,4};'...
    'set(h7listatotal,''string'',v7sigselect(:,1));'...
    'v7numsig=v7numsig+1;'];


h7addaprox=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'string','Ad. Aprox.',...
    'position',[0.83,0.41,0.07,0.04],...
    'callback',f7addapx_fcn);

h7detatxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.91,0.563,0.05,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','Detalhes');

h7listdetalhes=uicontrol('style','listbox',...
    'units','normalized',...
    'position',[0.91,0.46,0.077,0.1],...
    'backgroundcolor','white',...
    'enable','off',...
    'string','Nenhum');

f7adddet_fcn=['v7detselect=get(h7listdetalhes,''value'');'...
    'switch get(h7veropt,''value'');'...
        'case 1;'...
            'v7sigselect{v7numsig,1}=v7detname{v7detselect,1};'...
        'case 2;'...
            'v7sigselect{v7numsig,1}=v7detname{v7detselect,2};'...
    'end;'...
    'v7sigselect{v7numsig,2}=0;'...
    'v7sigselect{v7numsig,3}=v7detname{v7detselect,4};'...
    'set(h7listatotal,''string'',v7sigselect(:,1));'...
    'v7numsig=v7numsig+1;'];


h7addetalhe=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'string','Ad. Detalhe.',...
    'enable','off',...
    'position',[0.915,0.41,0.07,0.04],...
    'callback',f7adddet_fcn);

h7listatotaltxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.827,0.375,0.12,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','Sinais selecionados');

h7listatotal=uicontrol('style','listbox',...
    'units','normalized',...
    'position',[0.86,0.25,0.1,0.12],...
    'backgroundcolor','white',...
    'enable','off',...
    'string','Nenhum');

f7remover_fcn=['v7remsig=get(h7listatotal,''value'');'...
    'switch isempty(v7editmx);'...
        'case 0;'...
            'set([h7editsignaltxt h7selsignal h7edittodo h7editintervalo h7v1txt h7v1value h7editar],''enable'',''off'');'...
            'set([h7limitar h7limitarhist h7substituir],''enable'',''off'');'...
            'v7editlist=cell2mat(v7editmx(:,3));'...
            'v7editin=find(v7editlist==v7remsig);'...
            'switch isempty(v7editin);'...
                'case 0;'...
                    'v7editmx(v7editin,:)=[];'...
                    'if v7nedit>1;'...
                        'for i=v7nedit-1:-1:1;'...
                            'switch isempty(v7plotedit{v7editin,i});'...
                                'case 0;'...
                                    'v7plotedit(:,i)=[];'...
                                    'v7nedit=v7nedit-1;'...
                            'end;'...
                            'if v7remsig==v7cdataedit{i,4};'...
                                'v7c(v7cdataedit{i,1}:v7cdataedit{i,2})=v7cdataedit{i,3};'...
                                'v7cdataedit(i,:)=[];'...
                            'else;'...
                                'if v7cdataedit{i,4}>v7remsig;'...
                                    'v7cdataedit{i,4}=v7cdataedit{i,4}-1;'...
                                'end;'...
                            'end;'...
                        'end;'...
                    'v7plotedit(v7editin,:)=[];'...
                    'end;'...
                    'switch isempty(v7editmx);'...
                        'case 0;'...
                            'set(h7selsignal,''value'',1,''string'',v7editmx(:,1));'...
                            'eval(f7selsignal_fcn);'...
                        'case 1;'...
                            'set(h7selsignal,''value'',1,''string'',''Nenhum'');'...
                            'set(h7edittodo,''string'',''0'');'...
                            'set([h7pinicialvalue h7pfinalvalue],''string'',''1'');'...
                    'end;'...
            'end;'...
    'end;'...
    'v7numsig=v7numsig-1;'...
    'if v7numsig<2;'...
        'set(h7listatotal,''value'',1,''string'',''Nenhum'');'...
        'v7numsig=1;'...
        'return;'...
    'end;'...
    'v7sigselect(v7remsig,:)=[];'...
    'set(h7salvarsignal,''value'',1,''string'',''N/A'');'...
    'set([h7salvar h7salvarfig h7salvartxt h7salvarsignal h7editar],''enable'',''off'');'...
    'set(h7zoombutton,''enable'',''off'',''value'',0);'...
    'set(h7zoom,''enable'',''off'');'...
    'set(h7listatotal,''value'',1,''string'',v7sigselect(:,1));'];

h7remover=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'string','Remover',...
    'enable','off',...
    'position',[0.835,0.195,0.07,0.045],...
    'callback',f7remover_fcn);

f7visualizar_fcn=['v7altplot=v7hini/v7numsig;'...
    'switch isempty(h7axapdet);'...
        'case 0;'...
        'delete(h7axapdet);'...
        'h7axapdet=[];'...
    'end;'...
    'set(h7axesini,''position'',[0.056,0.165+(v7numsig-1)*v7altplot,0.755,(v7altplot-0.02)]);'...
    'v7editinx=1;'...
    'v7editmx=[];'...
    'switch iscell(get(h7listatotal,''string''));'...
        'case 0;'...
            'set(h7selsignal,''string'',''Nenhum'',''enable'',''off'');'...
            'set([h7salvartxt h7salvar h7salvarfig],''enable'',''off'');'...
            'set(h7salvarsignal,''enable'',''off'',''string'',''N/A'');'...
            'set([h7pinicialvalue h7pfinalvalue],''string'',''0'',''enable'',''off'');'...
            'set([h7editsignaltxt h7selsignal h7edittodo h7editintervalo h7v1txt h7v1value h7editar],''enable'',''off'');'...
            'set([h7limitar h7limitarhist h7substituir],''enable'',''off'');'...
            'return;'...
    'end;'...
    'for i=v7numsig:-1:2;'...
        'h7axapdet(i-1)=axes(''units'',''normalized'',''position'',[0.056,0.165+(i-2)*v7altplot,0.755,(v7altplot-0.022)]);'...
        'switch get(h7veropt,''value'');'...
            'case 1;'...
                'switch v7sigselect{v7numsig+1-i,2};'...
                    'case 0;'...
                        'v7dataplot=detcoef(v7c,v7l,v7sigselect{v7numsig+1-i,3});'...
                        'v7sigselect{v7numsig+1-i,4}=length(v7dataplot);'...
                        'v7editmx{v7editinx,1}=v7sigselect{v7numsig+1-i,1};'...
                        'v7editmx{v7editinx,2}=length(v7dataplot);'...
                        'v7editmx{v7editinx,3}=v7numsig+1-i;'...
                        'v7editmx{v7editinx,4}=v7sigselect{v7numsig+1-i,3};'...
                        'v7editinx=v7editinx+1;'...
                        'v7color=''r'';'...
                    'case 1;'...
                        'v7dataplot=appcoef(v7c,v7l,v7wname,v7sigselect{v7numsig+1-i,3});'...
                        'v7sigselect{v7numsig+1-i,4}=length(v7dataplot);'...
                        'v7color=''b'';'...
                        'if v7sigselect{v7numsig+1-i,3}==v7level;'...
                            'v7editmx{v7editinx,1}=v7sigselect{v7numsig+1-i,1};'...
                            'v7editmx{v7editinx,2}=length(v7dataplot);'...
                            'v7editmx{v7editinx,3}=v7numsig+1-i;'...
                            'v7editmx{v7editinx,4}=0;'...
                            'v7editinx=v7editinx+1;'...
                        'end;'...
                'end;'...
                'v7label=v7sigselect{v7numsig+1-i,1};'...
                'v7plotapdet(v7numsig+1-i)=plot(v7dataplot,v7color);'...
                'grid on;'...
                'ylabel(v7label);'...
                'axis tight;'...
            'case 2;'...
                'switch v7sigselect{v7numsig+1-i,2};'...
                    'case 0;'...
                        'v7color=''r'';'...
                        'v7detapx=''d'';'...
                    'case 1;'...
                        'v7color=''b'';'...
                        'v7detapx=''a'';'...
                'end;'...
                'v7dataplot=wrcoef(v7detapx,v7c,v7l,v7wname,v7sigselect{v7numsig+1-i,3});'...
                'v7sigselect{v7numsig+1-i,4}=length(v7dataplot);'...
                'v7label=v7sigselect{v7numsig+1-i,1};'...
                'v7plotapdet(v7numsig+1-i)=plot(v7t,v7dataplot,v7color);'...
                'grid on;'...
                'ylabel(v7label);'...
                'axis tight;'...
        'end;'...
    'end;'...
    'switch get(h7veropt,''value'');'...
        'case 1;'...
            'switch isempty(v7editmx);'...
                'case 0;'...
                    'set(h7selsignal,''value'',1,''string'',v7editmx(:,1));'...
                    'set(h7pfinalvalue,''string'',num2str(v7editmx{1,2}));'...
                    'set(h7pinicialvalue,''string'',''1'');'...
                    'set([h7editsignaltxt h7selsignal h7edittodo h7editintervalo h7v1txt h7v1value h7editar],''enable'',''on'');'...
                    'set([h7limitar h7limitarhist h7substituir],''enable'',''on'');'...
            'end;'...
         'case 2;'...
            'set(h7zoomconj,''enable'',''on'');'...
    'end;'...
    'set(h7axesini,''xlim'',[0 v7treg]);'...
    'set(h7salvarsignal,''value'',1,''string'',v7sigselect(:,1),''enable'',''on'');'...
    'set([h7salvartxt h7salvar h7salvarfig h7zoombutton h7zoomind],''enable'',''on'');'];

h7visualizar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'string','Visualizar',...
    'position',[0.91,0.195,0.07,0.045],...
    'callback',f7visualizar_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%ZOOM%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7frame4=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.822,0.02,0.17,0.1]);


f7zommpost_fcn=['if v7cax==h7axesini;'...
        'v7maxplot=v7treg;'...
        'v7minplot=0;'...
    'else;'...
        'switch get(h7veropt,''value'');'...
            'case 1;'...
                'v7zoomaxe=find(wrev(h7axapdet)==v7cax);'...
                'v7maxplot=v7sigselect{v7zoomaxe,4};'...
                'v7minplot=1;'...
            'case 2;'...
                'v7maxplot=v7treg;'...
                'v7minplot=0;'...
         'end;'...
     'end;'...
     'v7xlim=get(v7cax,''xlim'');'...
     'if v7xlim(1)<v7minplot;'...
        'v7xlim(1)=v7minplot;'...
     'end;'...
     'if v7xlim(2)>v7maxplot;'...
        'v7xlim(2)=v7maxplot;'...
     'end;'...
     'set(v7cax,''xlim'',v7xlim);'];

h7zoom=zoom(h7dwt);

f7zoom_fcn=['switch get(h7zoombutton,''value'');'...
        'case 0;'...
            'set(h7zoom,''enable'',''off'');'...
        'case 1;'...
            'set(h7zoom,''enable'',''on'',''actionpostcallback'',f7zommpost_fcn,''actionprecallback'',''v7cax=gca;axes(v7cax)'');'...
     'end;'];

h7zoombutton=uicontrol('style','toggle',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'string','Zoom',...
    'position',[0.835,0.0415,0.07,0.05],...
    'callback',f7zoom_fcn);

f7zoomind_fcn=['switch get(h7zoomind,''value'');'...
        'case 1;'...
            'set(h7zoomconj,''value'',0);'...
            'linkaxes([h7axesini h7axapdet],''off'');'...
        'case 0;'...
            'set(h7zoomind,''value'',1);'...
    'end;'];

h7zoomind=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'value',1,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.908,0.07,0.065,0.02],...
    'string','Individual',...
    'callback',f7zoomind_fcn);

f7zoomconj_fcn=['switch get(h7zoomconj,''value'');'...
        'case 1;'...
            'set(h7zoomind,''value'',0);'...
            'linkaxes([h7axesini h7axapdet]);'...
        'case 0;'...
            'set(h7zoomconj,''value'',1);'...
    'end;'];

h7zoomconj=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.908,0.04,0.065,0.02],...
    'string','Conjunto',...
    'callback',f7zoomconj_fcn);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%EDITAR config%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7frame5=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.056,0.02,0.45,0.1]);

h7editarlabel=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.06,0.085,0.1,0.023],...
    'fontname','arial',...
    'fontsize',v7letra+1,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','EDIÇÃO');

h7editsignaltxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.06,0.049,0.05,0.02],...
    'fontname','arial',...
    'enable','off',...
    'fontsize',v7letra,...
    'HorizontalAlignment','left',...
    'string','Sinal atual:');

f7selsignal_fcn=['v7editselect=get(h7selsignal,''value'');'...
    'v7p2ok=v7editmx{v7editselect,2};'...
    'set(h7pfinalvalue,''string'',num2str(v7p2ok));'...
    'v7p1ok=1;'...
    'set(h7pinicialvalue,''string'',''1'');'...
    'switch get(h7limitarhist,''value'');'...
        'case 1;'...
            'eval(f7deflim_fcn);'...
    'end;'];

h7selsignal=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'string','Nenhum',...
    'position',[0.11,0.026,0.07,0.05],...
    'callback',f7selsignal_fcn);

f7edittodo_fcn=['switch get(h7edittodo,''value'');'...
        'case 1;'...
            'set([h7pfinalvalue h7pinicialvalue],''enable'',''off'');'...
            'set(h7editintervalo,''value'',0);'...
            'eval(f7selsignal_fcn);'...
        'case 0;'...
            'set(h7edittodo,''value'',1);'...
    'end;'];

h7edittodo=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'value',1,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.185,0.036,0.045,0.02],...
    'string','Todo',...
    'callback',f7edittodo_fcn);

f7editintervalo_fcn=['switch get(h7editintervalo,''value'');'...
        'case 1;'...
            'set(h7edittodo,''value'',0);'...
            'set([h7pfinalvalue h7pinicialvalue],''enable'',''on'');'...
        'case 0;'...
            'set(h7editintervalo,''value'',1);'...
    'end;'];

h7editintervalo=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.185,0.076,0.055,0.02],...
    'string','Intervalo',...
    'callback',f7editintervalo_fcn);

h7pinicialtxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.245,0.077,0.02,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','P1');

f7pvalue_fcn=['try;'...
        'v7p1=str2num(get(h7pinicialvalue,''string''));'...
        'v7p2=str2num(get(h7pfinalvalue,''string''));'...
    'catch;'...
        'beep;'...
        'msgbox(''Valor invalido para P1 ou P2'',''Erro de definicao'',''warn'');'...
        'set(h7pinicialvalue,''string'',num2str(v7p1ok));'...
        'set(h7pfinalvalue,''string'',num2str(v7p2ok));'...
        'return;'...
    'end;'...
    'if v7p1>v7p2 || v7p1<1;'...
        'beep;'...
        'msgbox(''P1 deve ser maior ou igual a um e menor que P2'',''Erro de definicao'',''warn'');'...
        'set(h7pinicialvalue,''string'',num2str(v7p1ok));'...
        'set(h7pfinalvalue,''string'',num2str(v7p2ok));'...
        'return;'...
    'end;'...
    'if v7p2>v7editmx{get(h7selsignal,''value''),2};'...
        'beep;'...
        'msgbox(''P2 deve ser menor que o numero de dados do sinal'',''Erro de definicao'',''warn'');'...
        'set(h7pfinalvalue,''string'',num2str(v7p2ok));'...
        'return;'...
    'end;'...
    'v7p1ok=v7p1;'...
    'v7p2ok=v7p2;'];


h7pinicialvalue=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'string','0',...
    'enable','off',...
    'backgroundcolor','white',...
    'position',[0.26,0.076,0.04,0.028],...
    'callback',f7pvalue_fcn);

h7pfinaltxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.245,0.031,0.02,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','P2');

h7pfinalvalue=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'string','0',...
    'enable','off',...
    'backgroundcolor','white',...
    'position',[0.26,0.03,0.04,0.028],...
    'callback',f7pvalue_fcn);

f7limitar_fcn=['switch get(h7limitar,''value'');'...
        'case 0;'...
            'set(h7limitar,''value'',1);'...
        'case 1;'...
            'set([h7substituir h7limitarhist],''value'',0);'...
            'set([h7v1value h7v1txt h7v2value h7v2txt],''enable'',''on'');'...
            'v7v2ok=-1;'...
     'end;'...
     'set(h7v1value,''string'',''0'');'...
     'set(h7v2value,''string'',''-1'');'];

h7limitar=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.31,0.056,0.055,0.02],...
    'string','Limitar',...
    'callback',f7limitar_fcn);


  f7deflim_fcn=['v7selcoef=get(h7selsignal,''value'');'...
      'v7histdata=get(v7plotapdet(v7selcoef),''ydata'');'...
      'if v7editmx{v7selcoef,4}==0;'...
          'v7prc1=prctile(v7histdata,25);'...
          'v7prc2=prctile(v7histdata,75);'...
        'else;'...
          'v7prc1=prctile(v7histdata,5);'...
          'v7prc2=prctile(v7histdata,95);'...
      'end;'...
      'set(h7v2value,''string'',num2str(v7prc1));'...
      'set(h7v1value,''string'',num2str(v7prc2));'];

f7limhist_fcn=['switch get(h7limitarhist,''value'');'...
    'case 0;'...
        'set(h7limitarhist,''value'',1);'...
    'case 1;'...
        'set([h7limitar h7substituir],''value'',0);'...
        'set([h7v1value h7v1txt h7v2value h7v2txt],''enable'',''off'');'...
    'end;'...
    'eval(f7deflim_fcn);'];

h7limitarhist=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.31,0.026,0.06,0.02],...
    'string','EOG',...
    'callback',f7limhist_fcn);

f7subs_fcn=['switch get(h7substituir,''value'');'...
        'case 0;'...
            'set(h7substituir,''value'',1);'...
        'case 1;'...
            'set([h7limitar h7limitarhist],''value'',0);'...
            'set([h7v1value h7v1txt],''enable'',''on'');'...
            'set([h7v2value h7v2txt],''enable'',''off'');'...
     'end;'...
     'set(h7v1value,''string'',''0'');'...
     'set(h7v2value,''string'',''-1'');'];

h7substituir=uicontrol('style','radio',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'value',1,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'position',[0.31,0.086,0.057,0.02],...
    'string','Substituir',...
    'callback',f7subs_fcn);

h7v1txt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.373,0.076,0.06,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','V1');

f7v1check_fcn=['try;'...
        'v7v2=str2num(get(h7v2value,''string''));'...
        'v7v1=str2num(get(h7v1value,''string''));'...
    'catch;'...
        'beep;'...
        'msgbox(''Valor invalido V1'',''Erro de definicao'',''warn'');'...
        'return;'...
    'end;'...
    'switch get(h7limitar,''value'');'...
        'case 1;'...
            'if v7v2>v7v1;'...
                'beep;'...
                'msgbox(''V1 deve ser maior que V2'',''Erro de definicao'',''warn'');'...
                'set(h7v2value,''string'',num2str(v7v1ok));'...
                'return;'...
            'end;'...
            'v7v1ok=v7v1;'...
      'end;'];

h7v1value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'string','0',...
    'enable','off',...
    'backgroundcolor','white',...
    'position',[0.388,0.076,0.04,0.028],...
    'callback',f7v1check_fcn);

h7v2txt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.373,0.03,0.06,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','V2');

f7v2check_fcn=['try;'...
        'v7v2=str2num(get(h7v2value,''string''));'...
        'v7v1=str2num(get(h7v1value,''string''));'...
    'catch;'...
        'beep;'...
        'msgbox(''Valor invalido V2'',''Erro de definicao'',''warn'');'...
        'return;'...
    'end;'...
    'if v7v2>v7v1;'...
        'beep;'...
        'msgbox(''V2 deve ser menor que V1'',''Erro de definicao'',''warn'');'...
        'set(h7v2value,''string'',num2str(v7v2ok));'...
        'return;'...
    'end;'...
    'v7v2ok=v7v2;'];

h7v2value=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'string','-1',...
    'enable','off',...
    'backgroundcolor','white',...
    'position',[0.388,0.03,0.04,0.028],...
    'callback',f7v2check_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%EDITAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f7editar_fcn=['try;'...
        'v7newvalue=str2num(get(h7v1value,''string''));'...
     'catch;'...
        'beep;'...
        'msgbox(''Valor invalido para o novo valor'',''Erro de definicao'',''warn'');'...
        'set(h7v1value,''string'',''0'');'...
        'return;'...
     'end;'...
     'v7signaledit=v7editmx{get(h7selsignal,''value''),3};'...
     'v7leveledit=v7editmx{get(h7selsignal,''value''),4};'...
     'v7plotedit1=str2num(get(h7pinicialvalue,''string''));'...
     'v7plotedit2=str2num(get(h7pfinalvalue,''string''));'...
     'if v7leveledit==0;'...
         'v7ceditp1=v7plotedit1;'...
         'v7ceditp2=v7plotedit2;'...
     'else;'...
         'v7ptoini=0;'...
         'for v7ip=1:v7level-v7leveledit+1;'...
            'v7ptoini=v7ptoini+v7l(v7ip);'...
         'end;'...
         'v7ceditp1=v7ptoini+v7plotedit1;'...
         'v7ceditp2=v7ptoini+v7plotedit2;'...
     'end;'...
     'v7cdataedit{v7nedit,1}=v7ceditp1;'...
     'v7cdataedit{v7nedit,2}=v7ceditp2;'...
     'v7cdataedit{v7nedit,3}=v7c(v7ceditp1:v7ceditp2);'...
     'v7cdataedit{v7nedit,4}=v7signaledit;'...
     'v7dataedit=get(v7plotapdet(v7signaledit),''ydata'');'...
     'v7plotedit{v7signaledit,v7nedit}=v7dataedit;'...
     'switch get(h7substituir,''value'');'...
        'case 1;'...
            'v7c(v7ceditp1:v7ceditp2)=v7newvalue;'...
            'v7dataedit(v7plotedit1:v7plotedit2)=v7newvalue;'...
        'case 0;'...
            'v7max=str2num(get(h7v1value,''string''));'...
            'v7min=str2num(get(h7v2value,''string''));'...
            'for i=v7ceditp1:v7ceditp2;'...
                'if v7c(i)>v7max;'...
                    'v7c(i)=v7max;'...
                'else;'...
                    'if v7c(i)<v7min;'...
                        'v7c(i)=v7min;'...
                    'end;'...
                'end;'...
            'end;'...
            'for k=v7plotedit1:v7plotedit2;'...
                'if v7dataedit(k)>v7max;'...
                    'v7dataedit(k)=v7max;'...
                'else;'...
                    'if v7dataedit(k)<v7min;'...
                        'v7dataedit(k)=v7min;'...
                    'end;'...
                'end;'...
            'end;'...
     'end;'...
     'set(v7plotapdet(v7signaledit),''ydata'',v7dataedit);'...
     'axes(h7axapdet(v7numsig-v7signaledit));'...
     'axis tight;'...
     'v7nedit=v7nedit+1;'...
     'switch isempty(v7plotrec);'...
        'case 0;'...
            'delete(v7plotrec);'...
            'v7plotrec=[];'...
            'set(h7recon,''checked'',''off'');'...
            'set([h7saverecfig h7saverec],''enable'',''off'');'...
     'end;'...
     'set([h7desfazer h7reconstruir],''enable'',''on'');'];

% f7editar_fcn=['try;'...
%         'v7newvalue=str2num(get(h7v1value,''string''));'...
%      'catch;'...
%         'beep;'...
%         'msgbox(''Valor invalido para o novo valor'',''Erro de definicao'',''warn'');'...
%         'set(h7v1value,''string'',''0'');'...
%         'return;'...
%      'end;'...
%      'v7signaledit=v7editmx{get(h7selsignal,''value''),3};'...
%      'v7leveledit=v7editmx{get(h7selsignal,''value''),4};'...
%      'v7plotedit1=str2num(get(h7pinicialvalue,''string''));'...
%      'v7plotedit2=str2num(get(h7pfinalvalue,''string''));'...
%      'if v7leveledit==0;'...
%          'v7ceditp1=v7plotedit1;'...
%          'v7ceditp2=v7plotedit2;'...
%      'else;'...
%          'v7ceditp1=v7l(v7level-v7leveledit+2)+v7plotedit1;'...
%          'v7ceditp2=v7l(v7level-v7leveledit+2)+v7plotedit2;'...
%      'end;'...
%      'v7cdataedit{v7nedit,1}=v7ceditp1;'...
%      'v7cdataedit{v7nedit,2}=v7ceditp2;'...
%      'v7cdataedit{v7nedit,3}=v7c(v7ceditp1:v7ceditp2);'...
%      'v7cdataedit{v7nedit,4}=v7signaledit;'...
%      'v7dataedit=get(v7plotapdet(v7signaledit),''ydata'');'...
%      'v7plotedit{v7signaledit,v7nedit}=v7dataedit;'...
%      'switch get(h7substituir,''value'');'...
%         'case 1;'...
%             'v7c(v7ceditp1:v7ceditp2)=v7newvalue;'...
%             'v7dataedit(v7plotedit1:v7plotedit2)=v7newvalue;'...
%         'case 0;'...
%             'v7max=str2num(get(h7v1value,''string''));'...
%             'v7min=str2num(get(h7v2value,''string''));'...
%             'for i=v7ceditp1:v7ceditp2;'...
%                 'if v7c(i)<v7max;'...
%                     'if v7c(i)>v7min;'...
%                         'v7c(i)=0;'...
%                     'end;'...
%                 'end;'...
%             'end;'...
%             'for k=v7plotedit1:v7plotedit2;'...
%                 'if v7dataedit(k)<v7max;'...
%                     'if v7dataedit(k)>v7min;'...
%                         'v7dataedit(k)=0;'...
%                     'end;'...
%                 'end;'...
%             'end;'...
%      'end;'...
%      'set(v7plotapdet(v7signaledit),''ydata'',v7dataedit);'...
%      'axes(h7axapdet(v7numsig-v7signaledit));'...
%      'axis tight;'...
%      'v7nedit=v7nedit+1;'...
%      'switch isempty(v7plotrec);'...
%         'case 0;'...
%             'delete(v7plotrec);'...
%             'v7plotrec=[];'...
%             'set(h7recon,''checked'',''off'');'...
%             'set([h7saverecfig h7saverec],''enable'',''off'');'...
%      'end;'...
%      'set([h7desfazer h7reconstruir],''enable'',''on'');'];

h7editar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'enable','off',...
    'fontsize',v7letra,...
    'string','Editar',...
    'position',[0.43,0.068,0.07,0.04],...
    'callback',f7editar_fcn);

f7desfazer_fcn=['[v7fpedit v7cpedit]=size(v7plotedit);'...
    'for i=1:v7fpedit;'...
        'switch isempty(v7plotedit{i,v7nedit-1});'...
            'case 0;'...
                'set(v7plotapdet(i),''ydata'',v7plotedit{i,v7nedit-1});'...
                'axes(h7axapdet(v7numsig-i));'...
                'axis tight;'...
                'v7c(v7cdataedit{v7nedit-1,1}:v7cdataedit{v7nedit-1,2})=v7cdataedit{v7nedit-1,3};'...
        'end;'...
    'end;'...
    'v7cdataedit(v7nedit-1,:)=[];'...
    'v7plotedit(:,v7nedit-1)=[];'...
    'v7nedit=v7nedit-1;'...
    'if v7nedit==1;'...
        'set([h7desfazer h7reconstruir],''enable'',''off'');'...
    'end;'];

h7desfazer=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'string','Desfazer',...
    'position',[0.43,0.025,0.07,0.04],...
    'callback',f7desfazer_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%RECONSTRUIR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7frame6=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.664,0.02,0.148,0.1]);

f7reconstruir_fcn=['set([h7axapdet v7plotapdet],''visible'',''off'');'...
    'v7originpos=get(h7axesini,''position'');'...
    'set(h7axesini,''position'',[0.056,0.165,0.755,0.76]);'...
    'v7signalrec=waverec(v7c,v7l,v7wname);'...
    'axes(h7axesini);'...
    'hold on;'...
    'v7plotrec=plot(v7t,v7signalrec,''g'');'...
    'set([h7salvarfig h7salvar h7reconstruir h7desfazer h7editar],''enable'',''off'');'...
    'set([h7ver h7saverec h7saverecfig],''enable'',''on'');'...
    'set(h7recon,''checked'',''on'');'...
    'set(h7decom,''checked'',''off'');'];

h7reconstruir=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'enable','off',...
    'fontsize',v7letra,...
    'string','Reconstruir',...
    'position',[0.703,0.068,0.07,0.04],...
    'callback',f7reconstruir_fcn);

    % 'display(v7signalname);'...
    % 'display(v7filepath);'...
    % 'switch v7saveind;'...
    %     'case 1;'...
    %         '[v7savename v7savepath]=uiputfile(''*.ascii'',strcat(''Salvar registro_'',v7sigselect{v7savesignal,1}));'...
    %     'case 0;'...
    %         '[v7savename v7savepath]=uiputfile(''*.ascii'',''Salvar reconstrucao'');'...
    % 'end;'...
    % 'switch ischar(v7savename);'...
    %     'case 0;'...
    %         'return;'...
    % 'end;'...
f7salvar_fcn=['v7savesignal=get(h7salvarsignal,''value'');'...
    'v7savefile=strcat(v7filepath, v7signalname, ''R.ascii'');'...
    'switch v7saveind;'...
        'case 1;'...
            'v7datasaved=get(v7plotapdet(v7savesignal),''ydata'');'...%             'v7datasaved=((get(v7plotapdet(v7savesignal),''ydata'')+fc)/fb)-fa;'...
        'case 0;'...
            'v7datasaved=((get(v7plotrec,''ydata'')+fc)/fb)-fa;'...
    'end;'...
    'v7fid=fopen(v7savefile,''w'');'...
    'for i=1:length(v7datasaved);'...
        'fprintf(v7fid,''%f\n'',v7datasaved(i));'...
    'end;'...
    'fclose(v7fid);'];


h7saverec=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'enable','off',...
    'fontsize',v7letra,...
    'string','Salvar Dados',...
    'position',[0.667,0.025,0.07,0.04],...
    'callback','v7saveind=0;eval(f7salvar_fcn);');

f7salvarfig_fcn=['switch get(h7veropt,''value'');'...
        'case 1;'...
            'v7figcoef=1;'...
        'case 2;'...
            'clear v7figcoef;'...
    'end;'...
    'switch v7savefig;'...
        'case 1;'...
            'v7figsel=get(h7salvarsignal,''value'');'...
            'vfig_figydata=get(v7plotapdet(v7figsel),''ydata'');'...
            'vfig_figxdata=get(v7plotapdet(v7figsel),''xdata'');'...
            'vfig_figname=v7sigselect{v7figsel,1};'...
            'vfig_figcolor=get(v7plotapdet(v7figsel),''color'');'...
            'vfig_title=strcat(v7signalname,''-'',vfig_figname);'...
            'vfig_axeslim=get(h7axapdet(v7numsig-v7figsel),''xlim'');'...
            'switch get(h7veropt,''value'');'...
                'case 1;'...
                    'vfig_figyname=''Magnitude'';'...
                    'vfig_figxname=''Coeficientes'';'...
                'case 2;'...
                    'vfig_figyname=''Amplitude [uV]'';'...
                    'vfig_figxname=''Tempo [s]'';'...
            'end;'...
        'case 0;'...
            'clear v7figcoef;'...
            'vfig_axeslim=get(h7axesini,''xlim'');'...
            'vfig_title=strcat(''Reconstrucao de:'',v7signalname);'...
            'vfig_figydata=get(v7plotrec,''ydata'');'...
            'vfig_figxdata=get(v7plotrec,''xdata'');'...
            'vfig_figname=''Reconstrucao'';'...
            'vfig_figcolor=get(v7plotrec,''color'');'...
            'vfig_figxname=''Tempo [s]'';'...
            'vfig_figyname=''Amplitude [uV]'';'...
    'end;'...
    'exportfig;'];

h7saverecfig=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'enable','off',...
    'fontsize',v7letra,...
    'string','Salvar Figura',...
    'position',[0.739,0.025,0.07,0.04],...
    'callback','v7savefig=0;eval(f7salvarfig_fcn);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%SALVAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h7frame7=uicontrol('style','frame',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.51,0.02,0.149,0.1]);

h7salvarsignal=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'string','N/A',...
    'position',[0.565,0.056,0.05,0.05]);

h7salvartxt=uicontrol('style','text',...
    'backgroundcolor',[0.93 0.93 0.93],...
    'units','normalized',...
    'position',[0.535,0.079,0.03,0.02],...
    'fontname','arial',...
    'fontsize',v7letra,...
    'enable','off',...
    'HorizontalAlignment','left',...
    'string','Sinal');


h7salvar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'enable','off',...
    'fontsize',v7letra,...
    'string','Salvar Dados',...
    'position',[0.513,0.025,0.07,0.04],...
    'callback','v7saveind=1;eval(f7salvar_fcn);');


h7salvarfig=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'enable','off',...
    'fontsize',v7letra,...
    'string','Salvar Figura',...
    'position',[0.585,0.025,0.07,0.04],...
    'callback','v7savefig=1;eval(f7salvarfig_fcn);');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%REINICIAR%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


f7reset_fcn=['v7resetqtn=questdlg(''Deseja reiniciar o modulo?'',''Reiniciar'',''Sim'',''Não'',''Sim'');'...
    'switch strcmp(''Sim'',v7resetqtn);'...
        'case 1;'...
            'set([h7tipowave h7level h7veropt],''value'',1,''enable'',''off'');'...
            'set(h7paramwave,''visible'',''off'',''value'',1);'...
            'set(h7signaltxt,''string'',''Sinal:'');'...
            'set(h7tregtxt,''string'',''Tempo de registro [s]:'');'...
            'set(h7wavetxt,''string'',''Wavelet:'');'...
            'set([h7veraproxradio h7verdetalradio h7editintervalo h7zoomconj h7limitar h7limitarhist],''enable'',''off'',''value'',0);'...
            'set([h7v1value h7pfinalvalue h7pinicialvalue],''string'',''0'',''enable'',''off'');'...
            'set(h7v2value,''string'',''-1'',''enable'',''off'');'...
            'set([h7verdefradio h7edittodo h7zoomind h7substituir],''enable'',''off'',''value'',1);'...
            'set([h7original h7recon],''checked'',''on'');'...
            'set(h7decom,''checked'',''off'');'...
            'set(h7zoom,''enable'',''off'');'...
            'set(h7zoombutton,''value'',0,''enable'',''off'');'...
            'set(h7salvarsignal,''value'',1,''string'',''N/A'',''enable'',''off'');'...
            'set([h7listaprox h7listdetalhes h7listatotal h7selsignal],''value'',1,''string'',''Nenhum'',''enable'',''off'');'...
            'set([h7tipowavetxt h7laveltxt h7calcular h7ver h7visualizar h7addetalhe h7addaprox h7remover],''enable'',''off'');'...
            'set([h7salvar h7salvarfig h7saverec h7saverecfig h7reconstruir h7desfazer h7editar h7reset],''enable'',''off'');'...
            'switch isempty(h7axapdet);'...
                'case 0;'...
                    'delete(h7axapdet);'...
                    'h7axapdet=[];'...
            'end;'...
            'delete(v7plotsig);'...
            'set(h7axesini,''position'',[0.056,0.165,0.755,0.76]);'...
            'v7numsig=1;'...
            'v7nedit=1;'...
            'v7editmx=[];'...
            'switch isempty(v7plotrec);'...
                'case 0;'...
                    'delete(v7plotrec);'...
                    'v7plotrec=[];'...
            'end;'...
     'end;'];

h7reset=uicontrol('style','pushbutton',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',v7letra,...
    'string','Reiniciar',...
    'enable','off',...
    'position',[0.872,0.14,0.07,0.045],...
    'callback',f7reset_fcn);
