
%MODULO DE FOURIER

fft_enable=1;
v1treg=0;
v1enableind=0;
v1fstext=num2str(fs);
v1numsig=1;
v1ampmax=0;
v1ampmin=100000;
v1newfftind=0;
v1tempind=0;
v1fminiok=0;
v1fmaxok=fs/2;
v1tinicialok=0;
v1errorfile=0;
v1expind=0;
v1figurecolor=[251/255 252/255 207/255];
v1framecolor=[0.93 0.93 0.93];

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% CRIAR PAINEL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1fourier=figure('units','normalized',...
    'position',[0.0038,0.0495,0.993,0.89],...
    'menubar','none',...
    'numbertitle','off',...
    'name','Modulo de Fourier',...
    'color','white',...
    'deletefcn','clear h1* v1* f1*;calcok=0;fft_enable=0;');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  INFO %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h1frame1=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.815,0.84,0.175,0.11]);

h1infolabel=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.82,0.915,0.15,0.023],...
    'fontname','arial',...
    'fontsize',10,...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'string','PARÂMETROS BASE');

h1fstext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.82,0.88,0.167,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string',strcat('Fs [Hz]:',num2str(fs)));

h1janelatxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.82,0.85,0.16,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Janela: Hamming ');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% SINAIS APRESENTADOS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h1frame2=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.815,0.495,0.175,0.33]);

h1tempolabel=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.82,0.565,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tempo de registro [s]: ');

h1sintext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.82,0.785,0.15,0.03],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','REGISTROS');

f1list_fcn=['v1sigsel=get(h1listsignal,''value'');'...
     'set(h1tempolabel,''string'',strcat(''Tempo de registro [s]:'',num2str(v1tregind(v1sigsel))));'...
     'eval(f1potencia_fcn)'];

h1listsignal=uicontrol('style','listbox',...
    'units','normalized',...
    'position',[0.82,0.6,0.165,0.19],...
    'backgroundcolor','white',...
    'string','Nenhum',...
    'callback',f1list_fcn);

f1apagar_callback=['v1sindel=get(h1listsignal,''value'');'...
        'v1numsig=v1numsig-1;'...
        'v1colorindex=v1colormatindex(v1sindel);'...
        'v1colorname{v1colorindex,2}=0;'...
        'v1colormatindex(v1sindel)=[];'...
        'v1signalploted(v1sindel)=[];'...
        'v1saveplot(v1sindel)=[];'...
        'v1signalname(v1sindel)=[];'...
        'v1tregind(v1sindel)=[];'...
        'v1maxsignal(v1sindel)=[];'...
        'v1minsignal(v1sindel)=[];'...
        'v1maxspec(v1sindel)=[];'...
        'v1vaz=isempty(v1signalploted);'...
        'if v1vaz==1;'...
            'v1numsig=v1numsig+1;'...
            'eval(h1limpar_callback);'...
        'else;'...
             'delete(v1p(v1sindel));'...
             'v1p(v1sindel)=[];'...
             'v1tregmin=min(v1tregind);'...
             'v1treg=max(v1tregind);'...
             'set(h1listsignal,''value'',1,''string'',v1signalploted);'...
             'set(h1savesig,''value'',1,''string'',v1saveplot);'...
             'set(h1tempolabel,''string'',strcat(''Tempo de registro [s]:'',num2str(v1tregind(1))));'...
             'if v1tempind==1;'...
                 'delete(v1pt(v1sindel));'...
                 'v1pt(v1sindel)=[];'...
                 'set(h1axestempo,''ylim'',[min(v1minsignal) max(v1maxsignal)]);'...
                 'v1postdelaxis=get(h1axestempo,''xlim'');'...
                 'if v1postdelaxis(2)>v1treg;'...
                    'set(h1axestempo,''xlim'',[v1postdelaxis(1) v1treg]);'...
                 'end;'...
             'end;'...
             'set(h1axesfourier,''ylim'',[0 max(v1maxspec)]);'...
        'end;'];

h1apagar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.85,0.51,0.1,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Ocultar sinal',...
    'callback',f1apagar_callback);



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% AREA DE PLOTAGEM %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h1axesfourier=axes('units','normalized',...
    'position',[0.056,0.2,0.74,0.75],...
    'box','on');
grid on;
set(h1axesfourier,'xlim',[0 fs/2]);
ylabel('Potência','fontsize',9,'fontname','arial');
xlabel('Freqüência [Hz]','fontsize',9,'fontname','arial');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% AJUSTE DE EIXOS  EM FREQUENCIA%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1frame6=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.537,0.02,0.26,0.135]);

h1ajustfreqtxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.542,0.115,0.2,0.02],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','AJUSTE DA ESCALA DE FREQÜÊNCIA');


h1frectext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.542,0.075,0.105,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Intervalo de freqüência:');

f1popfrec_callback=['v1select=get(h1popfrec,''value'');'...
        'switch v1select;'...
            'case 1;'...
               'if v1enableind==1;'...
                  'set([h1adjustfreq h1fmintext h1fmaxtext h1fminvalue h1fmaxvalue],''enable'',''off'');'...
                  'v1enableind=0;'...
               'end;'...
               'axes(h1axesfourier);'...
               'if v1newfftind==0;'...
                    'axis([0 fs/2 0 abs(max(v1frecsignal))]);'...
               'else;'...
                    'axis([0 fs/2 0 abs(max(v1newfft))]);'...
               'end;'...
               'set(h1fminvalue,''string'',''0'');'...
               'set(h1fmaxvalue,''string'',num2str(fs/2));'...
            'case 2;'...
               'set([h1fmintext h1fmaxtext h1fminvalue h1fmaxvalue],''enable'',''on'');'...
               'v1enableind=1;'...
        'end;'];

h1popfrec=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'units','normalized',...
    'position',[0.645,0.053,0.065,0.05],...
    'string','0:Fs/2|Definir [Hz]',...
    'callback',f1popfrec_callback);

h1fmintext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.542,0.033,0.03,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmin:');

f1fvalue_callback=['v1fmax=str2num(get(h1fmaxvalue,''string''));'...
        'v1fmini=str2num(get(h1fminvalue,''string''));'...
        'if v1fmax>fs/2;'...
            'msgbox(''A frequência máxima deve ser menor de Fs/2'',''Erro de definição do intervalo de frequência'',''warn'');'...
            'set(h1fmaxvalue,''string'',num2str(v1fmaxok));'...
            'return;'...
        'end;'...
        'if v1fmax<v1fmini;'...
            'msgbox(''A frequência máxima deve ser maior do que a mínima'',''Erro de definição do intervalo de frequência'',''warn'');'...
            'set(h1fmaxvalue,''string'',num2str(v1fmaxok));'...
            'set(h1fminvalue,''string'',num2str(v1fminiok-1));'...
            'return;'...
        'end;'...
        'if v1fmini<0;'...
            'msgbox(''A frequência mínima deve ser positiva'',''Erro de definição do intervalo de frequência'',''warn'');'...
            'set(h1fminvalue,''string'',num2str(v1fminiok-1));'...
            'return;'...
        'end;'...
        'if v1newfftind==0;'...
            'v1fminipoint=floor(v1fmini*length(v1frecsignal)/fs);'...
            'v1fmaxpoint=floor(v1fmax*length(v1frecsignal)/fs);'...
            'axes(h1axesfourier);'...
            'axis([v1fmini v1fmax 0 abs(max(v1frecsignal(v1fminipoint+1:v1fmaxpoint)))]);'...
            'v1fminiok=v1fmini;'...
            'v1fmaxok=v1fmax;'...
        'else;'...
            'v1fminipoint=floor(v1fmini*length(v1newfft)/fs);'...
            'v1fmaxpoint=floor(v1fmax*length(v1newfft)/fs);'...
            'axes(h1axesfourier);'...
            'axis([v1fmini v1fmax 0 abs(max(v1newfft(v1fminipoint+1:v1fmaxpoint)))]);'...
            'v1fminiok=v1fmini;'...
            'v1fmaxok=v1fmax;'...
        'end;'...
        'eval(f1potencia_fcn);'...
        'set(h1adjustfreq,''enable'',''off'');'];

f1activefrqadj_callback='set(h1adjustfreq,''enable'',''on'');';

h1fminvalue=uicontrol('style','edit',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.57,0.03,0.033,0.025],...
    'callback',f1activefrqadj_callback);

h1adjustfreq=uicontrol('style','pushbutton',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','Ajustar',...
    'position',[0.723,0.027,0.07,0.05],...
    'callback',f1fvalue_callback);

h1fmaxtext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.63,0.033,0.03,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Fmax:');

h1fmaxvalue=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string',num2str(fs/2),...
    'backgroundcolor','white',...
    'position',[0.662,0.033,0.033,0.025],...
    'callback',f1activefrqadj_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% COLORMATRIX %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

v1colorname{1,1}='Azul'; v1colorname{1,2}=0; v1colorname{1,3}='b';
v1colorname{2,1}='Vermelho'; v1colorname{2,2}=0; v1colorname{2,3}='r';
v1colorname{3,1}='Verde'; v1colorname{3,2}=0; v1colorname{3,3}='g';
v1colorname{4,1}='Preto'; v1colorname{4,2}=0; v1colorname{4,3}='k';
v1colorname{5,1}='Amarelo'; v1colorname{5,2}=0; v1colorname{5,3}='y';
v1colorname{6,1}='Ciam'; v1colorname{6,2}=0; v1colorname{6,3}='c';
v1colorname{7,1}='Magenta'; v1colorname{7,2}=0; v1colorname{7,3}='m';

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% LIMPAR GRAFICA %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1frame4=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.815,0.02,0.175,0.135]);

h1limpar_callback=['v7resetqtn=questdlg(''Deseja reiniciar o modulo?'',''Reiniciar'',''Sim'',''Não'',''Sim'');'...
    'switch strcmp(''Sim'',v7resetqtn);'...
        'case 1;'...
        'for i=1:v1numsig-1;'...
        'delete(v1p(i));'...
        'end;'...
        'for k=1:7;'...
            'v1colorname{k,2}=0;'...
        'end;'...
        'if v1tempind==1;'...
            'delete(h1axestempo);'...
            'v1tempind=0;'...
        'end;'...
        'set(h1axesfourier,''position'',[0.056,0.2,0.74,0.75]);'...
        'set(h1fftmenuvertsin,''checked'',''off'');'...
        'v1tempind=0;'...
        'v1signalploted=[];'...
        'v1saveplot=[];'...
        'v1signalname=[];'...
        'v1tregind=[];'...
        'v1maxsignal=[];'...
        'v1minsignal=[];'...
        'v1t=[];'...
        'v1treg=0;'...
        'set([h1listsignal h1savesig],''value'',1,''string'',''Nenhum'');'...
        'set(h1popfrec,''enable'',''on'',''value'',1);'...
        'set(h1tempolabel,''string'',''Tempo de registro [s]:'');'...
        'set(h1fourierzoom,''enable'',''off'');'...
        'set(h1fftmenuverzoom,''checked'',''off'');'...
        'set(h1fftmenujanela,''enable'',''on'');'...
        'set([h1zoombutton h1fftmenuver h1popfrec h1fmintext h1fmaxtext h1fminvalue h1fmaxvalue h1apagar h1limpar h1tempolabel],''enable'',''off'');'...
        'set([h1ajustempo h1adjustfreq h1tinicialtext h1tfinaltext h1tinicialvalue h1tfinalvalue h1fftmenuvertsin],''enable'',''off'');'...
        'set([h1calcpot h1potenciatxt h1potsignal h1potinterval h1deltatxt h1thetatxt h1alphatxt h1bethatxt h1gammatxt ],''enable'',''off'');'...
        'set(h1fminvalue,''string'',''0'');'...
        'set([h1savesig h1expdados h1expfig h1pototal],''enable'',''off'');'...
        'axis([0 1 0 1]);'...
        'set(h1fmaxvalue,''string'',num2str(fs/2));'...
        'v1numsig=1;'...
        'clear v1p;'...
        'clear v1pt;'...
     'end;'];


h1limpar=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.85,0.028,0.1,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Reiniciar',...
    'callback',h1limpar_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% AJUSTE DE EIXOS  EM TEMPO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h1frame5=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.056,0.02,0.25,0.135]);

h1ajustempotxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.06,0.115,0.2,0.02],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','AJUSTE DA ESCALA DE TEMPO');

h1tempotext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.06,0.075,0.1,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Intervalo de Tempo [s]:');

f1tvalue_callback=['v1tinicial=str2num(get(h1tinicialvalue,''string''));'...
        'v1tfinal=str2num(get(h1tfinalvalue,''string''));'...
        'if v1tfinal>v1treg;'...
            'msgbox(''O tempo máximo deve ser menor do tempo de registro'',''Erro de definição'',''warn'');'...
            'set(h1tfinalvalue,''string'',num2str(v1tfinalok));'...
            'return;'...
        'end;'...
        'if v1tfinal<v1tinicial;'...
            'msgbox(''O tempo máximo deve ser maior do que a mínimo'',''Erro de definição'',''warn'');'...
            'set(h1tinicialvalue,''string'',num2str(v1tinicialok));'...
            'set(h1tfinalvalue,''string'',num2str(v1tfinalok));'...
            'return;'...
        'end;'...
        'if v1tinicial<0;'...
            'msgbox(''O tempo mínimo deve ser positivo'',''Erro de definição'',''warn'');'...
            'set(h1tinicialvalue,''string'',num2str(v1tinicialok));'...
            'return;'...
        'end;'...
        'v1tpointinicial=round((v1tinicial*fs)+1);'...
        'v1tpointfinal=round(v1tfinal*fs);'...
        'v1tpointfinalref=v1tpointfinal;'...
        'v1jandata=eval(strcat(v1janela,''('',num2str(v1tpointfinal-v1tpointinicial+1),'');''));'...
        'for i=1:length(v1pt);'...
            'v1dados=get(v1pt(i),''ydata'');'...
            'if length(v1dados)<v1tpointfinal;'...
                'v1tpointfinalref=length(v1dados);'...
            'end;'...
            'v1jandata=eval(strcat(v1janela,''('',num2str(v1tpointfinalref-v1tpointinicial+1),'');''));'...
            'v1ampmaxtemp=max(v1dados(v1tpointinicial:v1tpointfinalref));'...
            'v1ampmintemp=min(v1dados(v1tpointinicial:v1tpointfinalref));'...
            'if v1ampmaxtemp<v1maxsignal(i);'...
                'v1maxsignal(i)=v1ampmaxtemp;'...
            'end;'...
            'if v1ampmintemp>v1minsignal(i);'...
                'v1minsignal(i)=v1ampmintemp;'...
            'end;'...
            'v1prenewsignal=eval(v1signalname{i});'...
            'v1newsignal=((v1prenewsignal+fa)*fb)-fc;'...
            'v1newfft=fft(v1newsignal(v1tpointinicial:v1tpointfinalref).*v1jandata)./length(v1newsignal(v1tpointinicial:v1tpointfinalref));'...
            'v1maxspec(i)=max(abs(v1newfft));'...
            'v1newfaxis=0:fs/(length(v1newsignal(v1tpointinicial:v1tpointfinalref))-1):fs;'...
            'set(v1p(i),''xdata'',v1newfaxis,''ydata'',abs(v1newfft));'...
            'axes(h1axesfourier);'...
            'v1tpointfinalref=v1tpointfinal;'...
        'end;'...
        'axis([0 fs/2 0 max(v1maxspec)]);'...
        'set(h1fminvalue,''string'',''0'');'...
        'set(h1fmaxvalue,''string'',num2str(fs/2));'...
        'set(h1adjustfreq,''enable'',''off'');'...
        'v1newfftind=1;'...
        'axes(h1axestempo);'...
        'axis([v1tinicial v1tfinal min(v1minsignal) max(v1maxsignal)]);'...
        'v1tinicialok=v1tinicial;'...
        'v1tfinalok=v1tfinal;'...
        'eval(f1potencia_fcn);'...
        'set(h1ajustempo,''enable'',''off'');'];

f1activetadjust_callback='set(h1ajustempo,''enable'',''on'');';

h1tinicialtext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.06,0.033,0.035,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tinicial:');

h1tinicialvalue=uicontrol('style','edit',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.096,0.03,0.033,0.025],...
    'callback',f1activetadjust_callback);

h1tfinaltext=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.15,0.033,0.028,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Tfinal:');


h1tfinalvalue=uicontrol('style','edit',...
    'units','normalized',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','0',...
    'backgroundcolor','white',...
    'position',[0.18,0.03,0.033,0.025],...
    'callback',f1activetadjust_callback);

h1ajustempo=uicontrol('style','pushbutton',...
    'units','normalized',...
    'enable','off',...
    'fontname','arial',...
    'fontsize',9,...
    'string','Ajustar',...
    'position',[0.23,0.027,0.07,0.05],...
    'callback',f1tvalue_callback);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% CALCULO POTENCIAS%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

h1frame3=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.815,0.17,0.175,0.31]);


h1potenciatxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.82,0.44,0.13,0.02],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','POTÊNCIAS DO EEG');

h1potsignal=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.41,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Sinal:');

h1potinterval=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.385,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Intervalo [s]:');

h1deltatxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.36,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(deltaf1),':',num2str(deltaf2),' [Hz]'),...
    'string','Delta:');

h1thetatxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.335,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(thetaf1),':',num2str(thetaf2),' [Hz]'),...
    'string','Theta:');

h1alphatxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.31,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(alphaf1),':',num2str(alphaf2),' [Hz]'),...
    'string','Alpha:');

h1bethatxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.285,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(bethaf1),':',num2str(bethaf2),' [Hz]'),...
    'string','Betha:');

h1gammatxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.26,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'tooltipstring',strcat(num2str(gammaf1),':',num2str(gammaf2),' [Hz]'),...
    'string','Gamma:');

h1totaltxt=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
     'enable','off',...
    'units','normalized',...
    'position',[0.82,0.235,0.165,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Total:');

f1calcpot_fcn=['v1listselect=get(h1listsignal,''value'');'...
    'set([h1potenciatxt h1potsignal h1potinterval h1deltatxt h1thetatxt h1alphatxt h1bethatxt h1gammatxt h1totaltxt],''enable'',''on'');'...
    'set(h1potsignal,''string'',strcat(''Sinal: '',v1signalname{v1listselect}));',...
    'v1tcalfinal=str2num(get(h1tfinalvalue,''string''));'...
    'if v1tcalfinal>v1tregind(v1listselect);'...
        'v1tcalfinal=v1tregind(v1listselect);'...
    'end;'...
    'v1interval=strcat(''['',get(h1tinicialvalue,''string''),'':'',num2str(v1tcalfinal),'']'');'...
    'set(h1potinterval,''string'',strcat(''Intervalo [s]:'',v1interval));',...
    'v1specdata=get(v1p(v1listselect),''ydata'');'...
    'alphaf1p=round(alphaf1*length(v1specdata)/fs);'...
    'alphaf2p=round(alphaf2*length(v1specdata)/fs);'...
    'v1alphapot=0;'...
    'for i=alphaf1p:alphaf2p;'...
        'v1alphapot=v1alphapot+v1specdata(i).^2;'...
    'end;'...
    'bethaf1p=round(bethaf1*length(v1specdata)/fs);'...
    'bethaf2p=round(bethaf2*length(v1specdata)/fs);'...
    'v1bethapot=0;'...
    'for i=bethaf1p:bethaf2p;'...
        'v1bethapot=v1bethapot+v1specdata(i).^2;'...
    'end;'...
    'thetaf1p=round(thetaf1*length(v1specdata)/fs);'...
    'thetaf2p=round(thetaf2*length(v1specdata)/fs);'...
    'v1thetapot=0;'...
    'for i=thetaf1p:thetaf2p;'...
        'v1thetapot=v1thetapot+v1specdata(i).^2;'...
    'end;'...
    'deltaf1p=round(deltaf1*length(v1specdata)/fs);'...
    'deltaf2p=round(deltaf2*length(v1specdata)/fs);'...
    'v1deltapot=0;'...
    'for i=deltaf1p:deltaf2p;'...
        'v1deltapot=v1deltapot+v1specdata(i).^2;'...
    'end;'...
    'gammaf1p=round(gammaf1*length(v1specdata)/fs);'...
    'gammaf2p=round(gammaf2*length(v1specdata)/fs);'...
    'v1gammapot=0;'...
    'for i=gammaf1p:gammaf2p;'...
        'v1gammapot=v1gammapot+v1specdata(i).^2;'...
    'end;'...
    'v1totalpot=0;'...
    'for i=1:length(v1specdata)/2;'...
        'v1totalpot=v1totalpot+v1specdata(i).^2;'...
    'end;'...
    'if v1expind==1;;'...
        'return;'...
    'end;'...
    'set(h1alphatxt,''string'',strcat(''Alpha:'',num2str(v1alphapot)));'...
    'set(h1bethatxt,''string'',strcat(''Betha:'',num2str(v1bethapot)));'...
    'set(h1thetatxt,''string'',strcat(''Theta:'',num2str(v1thetapot)));'...
    'set(h1deltatxt,''string'',strcat(''Delta:'',num2str(v1deltapot)));'...
    'set(h1gammatxt,''string'',strcat(''Gamma:'',num2str(v1gammapot)));'...
    'set(h1totaltxt,''string'',strcat(''Total:'',num2str(v1totalpot)));'...
    'set(h1alphatxt,''tooltipstring'',strcat(num2str(alphaf1),'':'',num2str(alphaf2),'' [Hz]''));'...
    'set(h1gammatxt,''tooltipstring'',strcat(num2str(gammaf1),'':'',num2str(gammaf2),'' [Hz]''));'...
    'set(h1bethatxt,''tooltipstring'',strcat(num2str(bethaf1),'':'',num2str(bethaf2),'' [Hz]''));'...
    'set(h1thetatxt,''tooltipstring'',strcat(num2str(thetaf1),'':'',num2str(thetaf2),'' [Hz]''));'...
    'set(h1deltatxt,''tooltipstring'',strcat(num2str(deltaf1),'':'',num2str(deltaf2),'' [Hz]''));'...
    'calcok=1;'];

h1calcpot=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.85,0.18,0.1,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Calcular',...
    'callback',f1calcpot_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% MENU ARQUIVO%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

f1errorsignal_fcn=['beep;'...
        'msgbox(''O arquivo nao tem formato compativel'',''Arquivo invalido'',''warn'');'...
        'v1errorfile=1;'];

f1addsignal_callback=['if v1numsig>7;'...
            'msgbox(''O numero maximo de sinais simultaneos e 7. Para inserir outro oculte um dos sinais atuais.'',''Numero maximo de sinais apresentados'',''warn'');'...
            'return;'...
        'end;'...
        '[v1signalext,v1filepath]=uigetfile(''*.ascii'',''Escolha o arquivo de registro'');'...
        'switch ischar(v1signalext);'...
            'case 0;'...
                'return;'...
        'end;'...
        'v1file=strcat(v1filepath,v1signalext);'...
        'eval(''load(v1file)'',f1errorsignal_fcn);'...
        'if v1errorfile==1;'...
            'v1errorfile=0;'...
            'return;'...
        'end;'...
        'h7msnimport=msgbox(''...importando sinal...'',''Espere'',''warn'');'...
        'figure(h1fourier);'...
        'v1signalname{v1numsig}=v1signalext(1:length(v1signalext)-6);'...
        'v1presignal=eval(v1signalname{v1numsig});'...
        'v1signal=((v1presignal+fa)*fb)-fc;'...
        'v1maxsignal(v1numsig)=max(v1signal);'...
        'v1minsignal(v1numsig)=min(v1signal);'...
        'v1lengthsignal(v1numsig)=length(v1signal);'...
        'v1faxis=0:fs/(length(v1signal)-1):fs;'...
        'v1t{v1numsig}=0:1/fs:(length(v1signal)-1)/fs;'...
        'v1tregind(v1numsig)=round(max(v1t{v1numsig}));'...
        'v1tregmin=min(v1tregind);'...
        'v1treg=round(max(v1tregind));'...
        'v1tregstr=sprintf(''%6.2f'',v1treg);'...
        'v1tfinalok=str2num(v1tregstr);'...
        'v1tempotext=strcat(''Tempo de registro [s]: '',v1tregstr);'...
        'set(h1tempolabel,''enable'',''on'',''string'',v1tempotext);'...
        'for i=1:7;'...
            'if v1colorname{i,2}==0;'...
                'v1colorstr=v1colorname{i,1};'...
                'v1colorname{i,2}=1;'...
                'v1colorplot=v1colorname{i,3};'...
                'v1colormatindex(v1numsig)=i;'...
                'break;'...
            'end;'...
        'end;'...
        'if v1tempind==1;'...
            'set([h1fftmenuvertsin h1tinicialvalue h1tfinalvalue h1tinicialtext h1tfinaltext],''enable'',''on'');'...
            'v1signmtxt=v1signalname{v1numsig};'...
            'axes(h1axestempo);'...
            'hold on;'...
            'v1pt(v1numsig)=plot(v1t{v1numsig},v1signal,v1colorplot);'...
            'grid on;'...
            'axis tight;'...
        'end;'...
        'set(h1tfinalvalue,''string'',v1tregstr);'...
        'v1jandata=eval(strcat(v1janela,''('',num2str(length(v1signal)),'');''));'...
        'v1signal=v1signal.*v1jandata;'...
        'v1frecsignal=fft(v1signal)./length(v1signal);'...
        'v1maxspec(v1numsig)=max(abs(v1frecsignal));'...
        'v1faxis=0:fs/(length(v1signal)-1):fs;'...
        'axes(h1axesfourier);'...
        'hold on;'...
        'v1p(v1numsig)=plot(v1faxis,abs(v1frecsignal),v1colorplot);'...
        'grid on;'...
        'axis tight;'...
        'set(h1axesfourier,''xlim'',[str2num(get(h1fminvalue,''string'')) str2num(get(h1fmaxvalue,''string''))]);'...
        'v1newfftind=0;'...
        'v1tempind=strcmp(get(h1fftmenuvertsin,''checked''),''on'');'...
        'v1sigtxt=strcat(v1signalname{v1numsig},'''',''('',v1colorstr,'')'');'...
        'v1signalploted{v1numsig}=v1sigtxt;'...
        'v1saveplot=v1signalploted;'...
        'v1saveplot{v1numsig+1}=''Todos'';'...
        'v1numsig=v1numsig+1;'...
        'set(h1listsignal,''string'',v1signalploted,''value'',v1numsig-1);'...
        'set(h1savesig,''string'',v1saveplot);'...
        'set(h1popfrec,''enable'',''on'',''value'',1);'...
        'set([h1fmintext h1fmaxtext h1fminvalue h1fmaxvalue h1fftmenujanela],''enable'',''off'');'...
        'set(h1fminvalue,''string'',''0'');'...
        'set(h1fmaxvalue,''string'',num2str(fs/2));'...
        'delete(h7msnimport);'...
        'set([h1calcpot h1zoombutton h1fftmenuvertsin h1limpar h1apagar h1fftmenuver],''enable'',''on'');'...
        'eval(f1potencia_fcn);'...
        'set([h1savesig h1expdados h1expfig h1pototal],''enable'',''on'');'];

h1fftmenuarquivo=uimenu('label','Arquivo');
h1fftmenuarquivoadd=uimenu(h1fftmenuarquivo,'label','Adicionar sinal','callback',f1addsignal_callback);

f1sair_fcn=['v7sairqtn=questdlg(''Deseja fechar o modulo?'',''Reiniciar'',''Sim'',''Não'',''Sim'');'...
    'switch strcmp(''Sim'',v7sairqtn);'...
        'case 1;'...
        'close(h1fourier);'...
        'clear h1* v1* f1*;'...
        'calcok=0;fft_enable=0;'...
        'end;'];

h1fftmenuarquivosair=uimenu(h1fftmenuarquivo,'label','Sair','separator','on',...
    'callback',f1sair_fcn);

h1menuconfig=uimenu('label','Configuração');
v1janela='hamming';
f1janelackeck_fcn='set([h1janelahamming h1janelagaussiana h1janelablackman h1janelahanning h1janelakaiser h1janelahann],''checked'',''off'')';
h1fftmenujanela=uimenu(h1menuconfig,'label','Janela');
f1hamming_fcn='eval(f1janelackeck_fcn);set(h1janelahamming,''checked'',''on'');set(h1janelatxt,''string'',''Janela: Hamming'');v1janela=''hamming'';';
h1janelahamming=uimenu(h1fftmenujanela,'label','Hamming','checked','on','callback',f1hamming_fcn);
f1gauss_fcn='eval(f1janelackeck_fcn);set(h1janelagaussiana,''checked'',''on'');set(h1janelatxt,''string'',''Janela: Gaussina'');v1janela=''gausswin'';';
h1janelagaussiana=uimenu(h1fftmenujanela,'label','Gaussiana','callback',f1gauss_fcn);
f1blackman_fcn='eval(f1janelackeck_fcn);set(h1janelablackman,''checked'',''on'');set(h1janelatxt,''string'',''Janela: Blackman'');v1janela=''blackman'';';
h1janelablackman=uimenu(h1fftmenujanela,'label','Blackman','callback',f1blackman_fcn);
f1hanning_fcn='eval(f1janelackeck_fcn);set(h1janelahanning,''checked'',''on'');set(h1janelatxt,''string'',''Janela: Hanning'');v1janela=''hanning'';';
h1janelahanning=uimenu(h1fftmenujanela,'label','Hanning','callback',f1hanning_fcn);
f1kaiser_fcn='eval(f1janelackeck_fcn);set(h1janelakaiser,''checked'',''on'');set(h1janelatxt,''string'',''Janela: Kaiser'');v1janela=''kaiser'';';
h1janelakaiser=uimenu(h1fftmenujanela,'label','Kaiser','callback',f1kaiser_fcn);
f1hann_fcn='eval(f1janelackeck_fcn);set(h1janelahann,''checked'',''on'');set(h1janelatxt,''string'',''Janela: Hann'');v1janela=''hann'';';
h1janelahann=uimenu(h1fftmenujanela,'label','Hann','callback',f1hann_fcn);

h1menuritmos=uimenu(h1menuconfig,'label','Ritmos EEG','callback','ritconfig');



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% MENU VER%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


f1vertempo_callback=['v1vervalue=get(h1fftmenuvertsin,''checked'');'...
        'v1tempoativado=strcmp(v1vervalue,''on'');'...
        'switch v1tempoativado;'...
            'case 0;'...
                'set([h1tinicialvalue h1tfinalvalue h1tinicialtext h1tfinaltext],''enable'',''on'');'...
                'set(h1axesfourier,''position'',[0.056,0.2,0.74,0.35]);'...
                'h1axestempo=axes(''position'',[0.056,0.62,0.74,0.35]);'...
                'for i=1:v1numsig-1;'...
                    'v1signmtxt=v1signalname{i};'...
                    'v1presignm=eval(v1signmtxt);'...
                    'v1signm=((v1presignm+fa)*fb)-fc;'...
                    'v1colorindex=v1colormatindex(i);'...
                    'v1colortemp=v1colorname{v1colorindex,3};'...
                    'v1pt(i)=plot(v1t{i},v1signm,v1colortemp);'...
                    'hold on;'...
                'end;'...
                'grid on;'...
                'axis tight;'...
                'set(h1axestempo,''xlim'',[str2num(get(h1tinicialvalue,''string'')) str2num(get(h1tfinalvalue,''string''))]);'...
                'ylabel(''Amplitude'',''fontsize'',9,''fontname'',''arial'');'...
                'xlabel(''Tempo [s]'',''fontsize'',9,''fontname'',''arial'');'...
                'set(h1fftmenuvertsin,''checked'',''on'');'...
                'v1tempind=1;'...
            'case 1;'...
                'set(h1tfinalvalue,''string'',v1tregstr);'...
                'set(h1tinicialvalue,''string'',''0'');'...
                'eval(f1tvalue_callback);'...
                'delete(h1axestempo);'...
                'set(h1axesfourier,''position'',[0.056,0.2,0.74,0.75]);'...
                'set([h1tinicialtext h1tinicialvalue h1tfinaltext h1tfinalvalue],''enable'',''off'');'...
                'set(h1fftmenuvertsin,''checked'',''off'');'...
                'v1tempind=0;'...
        'end;'];

h1fftmenuver=uimenu('label','Ver','enable','off');
h1fftmenuvertsin=uimenu(h1fftmenuver,'label','Sinais no tempo','callback',f1vertempo_callback);

h1viaualizar=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.82,0.124,0.13,0.02],...
    'fontname','arial',...
    'fontsize',10,...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'string','VISUALIZAÇÃO');

f1prezoom_fcn='v1xlimini=get(gca,''xlim'');';

f1postzoom_fcn=['v1currax=gca;'...
    'v1zoomscale=get(v1currax,''xlim'');'...
    'if v1zoomscale(1)<0;'...
        'v1zoomscale(1)=0;'...
    'end;'...
    'if v1currax==h1axesfourier;'...
        'if v1zoomscale(2)>fs/2;'...
            'v1zoomscale(2)=fs/2;'...
        'end;'...
        'set(h1fminvalue,''string'',sprintf(''%4.2f'',v1zoomscale(1)));'...
        'set(h1fmaxvalue,''string'',sprintf(''%4.2f'',v1zoomscale(2)));'...
        'set(h1axesfourier,''xlim'',v1zoomscale);'...
        'set([h1fmintext h1fmaxtext h1fminvalue h1fmaxvalue],''enable'',''on'');'...
        'set(h1popfrec,''value'',2);'...
        'v1fminiok=str2num(sprintf(''%4.2f'',v1zoomscale(1)));'...
        'v1fmaxok=str2num(sprintf(''%4.2f'',v1zoomscale(2)));'...
    'else;'...
        'axfin=sprintf(''%4.3f\t'',v1zoomscale);'...
        'axini=sprintf(''%4.3f\t'',v1xlimini);'...
        'if v1xlimini(2)>v1zoomscale(2);'...
            'if v1zoomscale(2)>v1tregmin;'...
                'msgbox(''O zoom so pode ser feito em intervalos validos para todos os registros'',''Atenção'',''warn'');'...
                'set(v1currax,''xlim'',v1xlimini);'...
                'return;'...
            'end;'...
        'end;'...
        'if v1zoomscale(2)>v1treg;'...
            'v1zoomscale(2)=v1treg;'...
        'end;'...
        'v1xlimini=v1zoomscale;'...
        'set(h1tinicialvalue,''string'',sprintf(''%4.2f'',v1zoomscale(1)));'...
        'set(h1tfinalvalue,''string'',sprintf(''%4.2f'',v1zoomscale(2)));'...
        'v1tinicialok=str2num(sprintf(''%4.2f'',v1zoomscale(1)));'...
        'v1tfinalok=str2num(sprintf(''%4.2f'',v1zoomscale(2)));'...
        'eval(f1tvalue_callback);'...
    'end;'];

f1zoom_fcn=['v1zoomind=strcmp(get(h1fftmenuverzoom,''checked''),''on'');'...
    'switch v1zoomind;'...
        'case 1;'...
            'set(h1fftmenuverzoom,''checked'',''off'');'...
            'set(h1fourierzoom,''enable'',''off'');'...
        'case 0;'...
            'set(h1fftmenuverzoom,''checked'',''on'');'...
            'set(h1fourierzoom,''enable'',''on'',''actionpostcallback'',f1postzoom_fcn,''actionprecallback'',f1prezoom_fcn);'...
    'end;'];

h1zoombutton=uicontrol('style','toggle',...
    'units','normalized',...
    'position',[0.85,0.075,0.1,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Zoom',...
    'callback',f1zoom_fcn);

h1fourierzoom=zoom;
h1fftmenuverzoom=uimenu(h1fftmenuver,'label','Zoom','separator','on','callback',f1zoom_fcn);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% POTOTAL %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1frame7=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.31,0.1,0.223,0.04]);

f1potencia_fcn=['v1frqint=get(h1axesfourier,''xlim'');'...
    'v1espectrodata=get(v1p(get(h1listsignal,''value'')),''ydata'');'...
    'v1pointint=round(v1frqint/fs*length(v1espectrodata));'...
    'v1pointint(1)=v1pointint(1)+1;'...
    'v1potenciaint=0;'...
    'for i=v1pointint(1):v1pointint(2);'...
        'v1potenciaint=v1potenciaint+v1espectrodata(i).^2;'...
    'end;'...
    'set(h1pototal,''string'',strcat(''Potencia do espectro:'',num2str(v1potenciaint)));'];


h1pototal=uicontrol('style','text',...
    'backgroundcolor',v1framecolor,...
    'enable','off',...
    'units','normalized',...
    'position',[0.315,0.11,0.2,0.02],...
    'fontname','arial',...
    'fontsize',9,...
    'HorizontalAlignment','left',...
    'string','Potencia do espectro:');


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% SALVAR %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
h1frame8=uicontrol('style','frame',...
    'backgroundcolor',v1framecolor,...
    'units','normalized',...
    'position',[0.31,0.02,0.223,0.07]);

h1savesig=uicontrol('style','popup',...
    'backgroundcolor','white',...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'units','normalized',...
    'position',[0.315,0.021,0.08,0.05],...
    'string','N/A');

        %'[v1savename v1savepath]=uiputfile(''*.ascii'',strcat(''Salvar sinal_'',v1saveplot{v1expselect}));'...
        %'switch ischar(v1savename);'...
        %    'case 0;'...
        %        'return;'...
        %'end;'...
        %'v1expind=0;'...
f1expdados_fcn=['v1expselect=get(h1savesig,''value'');'...
    'if v1expselect<v1numsig;'...
        'v1savefile=strcat(v1filepath, v1signalext(1:length(v1signalext)-7), ''P.ascii'');'...
        'set(h1listsignal,''value'',v1expselect);'...
        'eval(f1calcpot_fcn);'...
        'v1fid=fopen(v1savefile,''w'');'...
        'fprintf(v1fid,''\nSinal:\t%s\nTempo de registro [s]:\t%6.2f'',v1signalname{v1expselect},v1tregind(v1expselect));'...
        'fprintf(v1fid,''\nIntervalo [s]\t%s\nJanela\t%s\nFs [Hz]:\t%6.2f\n\n\n'',v1interval,v1janela,fs);'...
        'fprintf(v1fid,''Ritmo\tPotencia\n'');'...
        'fprintf(v1fid,''Delta\t%4.5f\nTetha\t%4.5f\nAlpha\t%4.5f\nBetha\t%4.5f\nGamma\t%4.5f\n\n'',v1deltapot,v1thetapot,v1alphapot,v1bethapot,v1gammapot);'...
        'fprintf(v1fid,''Total\t'');'...
        'fclose(v1fid);'...
    'else;'...
        '[v1savename v1savepath]=uiputfile(''*.ascii'',strcat(''Salvar sinal_'',v1saveplot{v1expselect}));'...
        'switch ischar(v1savename);'...
            'case 0;'...
                'return;'...
        'end;'...
        'v1expind=1;'...
        'v1savefile=strcat(v1savepath,v1savename);'...
        'eval(f1calcpot_fcn);'...
        'v1fid=fopen(v1savefile,''w'');'...
        'fprintf(v1fid,''\nIntervalo [s]\t%s\nJanela\t%s\nFs [Hz]:\t%6.2f\n\n\n'',v1interval,v1janela,fs);'...
        'fprintf(v1fid,''Sinal\tTempo de registro [s]:\tDelta\tTetha\tAlpha\tBetha\tGamma\tTotal\n'');'...
        'for k=1:v1numsig-1;'...
            'set(h1listsignal,''value'',k);'...
            'eval(f1calcpot_fcn);'...
            'fprintf(v1fid,''%s\t%6.2f\t'',v1signalname{k},v1tregind(k));'...
            'fprintf(v1fid,''%4.5f\t%4.5f\t%4.5f\t%4.5f\t%4.5f\t%4.5f\n'',v1deltapot,v1thetapot,v1alphapot,v1bethapot,v1gammapot,v1totalpot);'...
        'end;'...
        'fclose(v1fid);'...
        'v1expind=0;'...
    'end;'];

h1expdados=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.4,0.033,0.06,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Exportar',...
    'callback',f1expdados_fcn);

f1savefig_fcn=['v1figsel=get(h1savesig,''value'');'...
        'if v1figsel==v1numsig;'...
            'beep;'...
            'msgbox(''Nao podem ser exportadas todas as figuras simultaneamente'',''Erro'',''warn'');'...
            'return;'...
        'end;'...
        'vfig_figydata=get(v1p(v1figsel),''ydata'');'...
        'vfig_figxdata=get(v1p(v1figsel),''xdata'');'...
        'vfig_figcolor=get(v1p(v1figsel),''color'');'...
        'vfig_figname=v1signalploted{v1figsel};'...
        'vfig_figxname=''Frequencia [Hz]'';'...
        'vfig_title=v1signalname{v1figsel};'...
        'vfig_figyname=''Potencia'';'...
        'vfig_axeslim=get(h1axesfourier,''xlim'');'...
        'exportfig;'];

h1expfig=uicontrol('style','pushbutton',...
    'units','normalized',...
    'position',[0.465,0.033,0.06,0.045],...
    'fontname','arial',...
    'fontsize',9,...
    'enable','off',...
    'string','Salvar Fig',...
    'callback',f1savefig_fcn);
